apiVersion: cluster.ray.io/v1
kind: RayCluster
metadata:
  name: example-cluster
  namespace: jhub
spec:
  headPodType: rayHeadType
  headStartRayCommands:
  - ray stop
  - ulimit -n 65536; ray start --head --port=6379 --no-monitor --dashboard-host 0.0.0.0
  idleTimeoutMinutes: 5
  maxWorkers: 6
  podTypes:
  - maxWorkers: 0
    minWorkers: 0
    name: rayHeadType
    podConfig:
      apiVersion: v1
      kind: Pod
      metadata:
        generateName: ray-head-type-
      spec:
        containers:
        - args:
          - 'trap : TERM INT; sleep infinity & wait;'
          command:
          - /bin/bash
          - -c
          - --
          env:
          - name: RAY_gcs_server_rpc_server_thread_num
            value: "1"
          image: rayproject/ray:latest
          imagePullPolicy: Always
          name: ray-node
          ports:
          - containerPort: 6379
            protocol: TCP
          - containerPort: 10001
            protocol: TCP
          - containerPort: 8265
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        restartPolicy: Never
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
  - maxWorkers: 4
    minWorkers: 2
    name: rayWorkerType
    podConfig:
      apiVersion: v1
      kind: Pod
      metadata:
        generateName: ray-worker-type-
      spec:
        containers:
        - args:
          - 'trap : TERM INT; sleep infinity & wait;'
          command:
          - /bin/bash
          - -c
          - --
          env:
          - name: RAY_gcs_server_rpc_server_thread_num
            value: "1"
          image: rayproject/ray:latest
          imagePullPolicy: Always
          name: ray-node
          ports:
          - containerPort: 6379
            protocol: TCP
          - containerPort: 10001
            protocol: TCP
          - containerPort: 8265
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 2
              memory: 4Gi
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        restartPolicy: Never
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
  upscalingSpeed: 1
  workerStartRayCommands:
  - ray stop
  - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379