apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-mnist
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: docker.io/dayeye2006/pytorch-mnist:demo
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/mnist/src/mnist.py"
                - "--epochs=1"
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: docker.io/dayeye2006/pytorch-mnist:demo
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/mnist/src/mnist.py"
                - "--epochs=1"