name: Deploy doc site
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      
jobs:
  publish-doc-site:
    runs-on: ubuntu-latest
    steps:
    - name: Check out main
      uses: actions/checkout@v2

    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: docs/mkdocs.yml
        REQUIREMENTS: requirements.txt
